version: "2"
services:
 db:
   container_name: enemometro_db
   image: "mysql:5.7"
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_USERNAME: root
     MYSQL_PASSWORD: root
   networks:
     - internal
     - traefik
 web:
   container_name: enemometro
   depends_on:
      - "db"
   image: "enemometro:latest"
   labels:
      - "traefix.enable=true"
      - "traefik.http.routers.web.entrypoints=web"
      - "traefik.http.routers.web.rule=Host(`enemometro.inf.ufsm.br`)"
   environment:
    DB_USERNAME: root
    DB_PASSWORD: root
    DB_PORT: 3306
    RAILS_ENV: development
    DB_HOST: db
   command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
   networks:
     - internal
     - traefik
networks:
  traefik:
    external:
      name: traefik
