version: "2"
services:
 db:
   container_name: enemometro_db
   image: "mysql:5.7"
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_USERNAME: root
     MYSQL_PASSWORD: root
   networks:
     - default
 enemometro:
   depends_on:
      - "db"
   image: "enemometro:latest"
   labels:
      - "traefik.enable=true"
      - "traefik.http.routers.enemometro.rule=Host(`enemometro.inf.ufsm.br`)"
      - "traefik.http.routers.enemometro.entrypoints=web"
      - "traefik.docker.network=traefik"
   environment:
    DB_USERNAME: root
    DB_PASSWORD: root
    DB_PORT: 3306
    RAILS_ENV: development
    DB_HOST: db
   command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
   networks:
     - traefik
     - default
   ports:
     - "3000:3000"
networks:
  traefik:
    external:
      name: traefik
