version: "2"
services:
 db:
   image: "mysql:5.7"
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_USERNAME: root
     MYSQL_PASSWORD: root
   ports:
      - "3307:3306"
 web:
   depends_on:
      - "db"
   build: .
   environment:
    DB_USERNAME: root
    DB_PASSWORD: root
    DB_PORT: 3306
    RAILS_ENV: development
    DB_HOST: db
   command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
   ports:
      - "3000:3000"
   volumes:
      - ".:/appl"